import { Link, useLocation } from 'react-router-dom';
import { ArrowRight, FileText, ShieldCheck } from 'lucide-react';
import { MarketingShell, PageHero, usePageMeta } from '../components/marketing/MarketingShell';

const privacySections = [
  ['Scope and overview', 'This Privacy Policy explains how GitMentor handles information when you visit the public site, sign in with GitHub, connect a repository, use AI mentorship features, build a roadmap, track progress, or optionally connect Google Calendar.'],
  ['GitHub account information', 'When you sign in with GitHub, GitMentor receives information needed to establish your account, including your GitHub account identifier, username, avatar, and an authorization credential. Repository and contribution information available through the connected account may be processed to provide repository views, skill assessment, analytics, recommendations, and code review features.'],
  ['Optional Google Calendar information', 'Google Calendar is not required to use the core product. If you connect it, GitMentor receives your Google account identifier, email address, granted scopes, and authorization credentials needed to create, update, reconcile, and remove Build Day events. Calendar refresh credentials are encrypted by the application before storage.'],
  ['Information created in GitMentor', 'GitMentor stores product information associated with your account, which may include preferences, repository cache, skill profiles, progress events, project roadmaps, phases, tasks, learning materials, Build Days, insights, analytics, achievements, and mentor conversation context.'],
  ['How information is used', 'Information is used to authenticate your session; display connected repositories; generate skill assessments, project recommendations, roadmaps, task breakdowns, reviews, and mentor responses; synchronize optional calendar events; track progress; evaluate achievements; maintain security; troubleshoot failures; and operate the service.'],
  ['AI provider processing', 'Relevant prompts, repository context, project context, or structured task inputs may be sent to configured AI providers to generate the feature you request. GitMentor currently supports task-aware routing across configured Gemini and Groq providers. Do not submit passwords, API keys, private credentials, or sensitive personal information in prompts or repositories selected for AI analysis.'],
  ['Service providers and external services', 'GitMentor relies on third-party services that may include GitHub for identity and repository access, Google for optional Calendar access, MongoDB infrastructure for application data, AI model providers for requested mentorship features, and hosting providers for service delivery. Those providers handle information according to their own terms and privacy practices.'],
  ['Storage, security, and retention', 'GitMentor uses authenticated routes, signed sessions, authorization checks, state validation, and protected credential handling to reduce unauthorized access. No internet service is perfectly secure. Information is retained for as long as reasonably necessary to operate the product, maintain security, resolve disputes, or meet applicable obligations.'],
  ['Your choices and controls', 'You can choose not to connect Google Calendar, disconnect it through Settings, revoke application permissions from GitHub or Google account controls, and stop using the service. Depending on how GitMentor is operated, you may request access, correction, or deletion of account information through the project contact channel.'],
  ['Children and international use', 'GitMentor is intended for people able to authorize connected developer accounts and is not directed to children under the minimum age required to consent to online services in their location. Information may be processed in locations where GitMentor or its providers operate.'],
  ['Updates and contact', 'This policy may change as the product evolves. The effective date will be updated when revisions are published. For privacy questions or requests, use the GitMentor GitHub repository issue channel and avoid posting secrets or private credentials.'],
];

const termsSections = [
  ['Acceptance of these Terms', 'By accessing or using GitMentor, you agree to these Terms of Use. If you do not agree, do not use the service or connect an external account.'],
  ['Description of the service', 'GitMentor provides AI-assisted developer skill analysis, repository views and feedback, project recommendations, phased roadmaps, task breakdowns, mentorship, progress analytics, achievements, Build Day scheduling, and optional Google Calendar synchronization. Features may be added, changed, suspended, or discontinued.'],
  ['Eligibility and account responsibility', 'You must be able to form a binding agreement under the laws that apply to you. You are responsible for the GitHub account used to access GitMentor, for protecting your session, and for activity performed through your account.'],
  ['Connected accounts and authorization', 'You may connect only accounts, repositories, calendars, code, and information that you own or are authorized to use. You are responsible for maintaining appropriate permissions and for revoking access when it is no longer wanted.'],
  ['Acceptable use', 'You may not use GitMentor to violate law, infringe intellectual property or privacy rights, gain unauthorized access, distribute malicious software, expose credentials, interfere with the service, abuse provider APIs, or analyze code or data you are not authorized to access.'],
  ['Your code and content', 'You retain ownership of your code, prompts, and other content. You grant GitMentor the limited rights necessary to access, transmit, process, cache, and display that content solely to operate, secure, and support the features you request.'],
  ['AI-generated guidance', 'Skill assessments, recommendations, roadmaps, task plans, code reviews, and mentor responses are generated with automated systems and may be incomplete, outdated, or incorrect. They are educational and productivity guidance, not a guarantee of employment, security, legal compliance, code quality, or project success. You must review and test outputs before relying on them.'],
  ['Open-source software', 'Parts or all of GitMentor may be available under the license identified in its source repository. The source-code license governs your use of the source code; these Terms govern your use of any hosted GitMentor service.'],
  ['Third-party services', 'GitHub, Google, AI model providers, database services, and hosting providers are independent third parties. Their products are governed by separate terms and may change or become unavailable. GitMentor is not responsible for third-party services, content, policies, or outages.'],
  ['Availability and changes', 'GitMentor may be unavailable, interrupted, or contain errors. Access may be limited or terminated when necessary for security, maintenance, legal compliance, or enforcement of these Terms.'],
  ['Disclaimer of warranties', 'To the maximum extent permitted by applicable law, GitMentor is provided “as is” and “as available,” without express or implied warranties, including warranties of merchantability, fitness for a particular purpose, non-infringement, availability, or accuracy.'],
  ['Limitation of liability', 'To the maximum extent permitted by applicable law, GitMentor and its maintainers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for loss of data, code, opportunity, profits, or goodwill arising from use of the service.'],
  ['Changes to these Terms', 'These Terms may be revised as the service changes. The effective date will be updated when revisions are published. Continued use after updated Terms take effect means you accept the revision.'],
  ['Contact', 'Questions about these Terms may be submitted through the GitMentor GitHub repository. Do not include account credentials, tokens, private keys, or other secrets in a public issue.'],
];

const LegalPage = () => {
  const { pathname } = useLocation();
  const isPrivacy = pathname === '/privacy';
  const title = isPrivacy ? 'Privacy Policy' : 'Terms of Use';
  const sections = isPrivacy ? privacySections : termsSections;
  usePageMeta(title, isPrivacy ? 'Read how GitMentor handles GitHub, optional Google Calendar, application, and AI feature data.' : 'Read the terms governing access to and use of GitMentor.');
  return <MarketingShell>
    <PageHero compact eyebrow="LEGAL" title={title} description={`Effective August 26, 2026 · ${isPrivacy ? 'How GitMentor handles connected data and product information.' : 'The conditions that govern access to and use of GitMentor.'}`} />
    <section className="mk-legal"><div className="mk-container mk-legal-grid"><aside><span>ON THIS PAGE</span>{sections.map(([heading], index) => <a key={heading} href={`#legal-${index + 1}`}>{String(index + 1).padStart(2, '0')} {heading}</a>)}</aside><article><div className="mk-legal-intro"><ShieldCheck aria-hidden="true" /><p>This policy describes the current GitMentor implementation in clear product language. It is a draft for product use and should be reviewed by qualified legal counsel before a commercial launch.</p></div>{sections.map(([heading, body], index) => <section id={`legal-${index + 1}`} key={heading}><span>{String(index + 1).padStart(2, '0')}</span><div><h2>{heading}</h2><p>{body}</p></div></section>)}<div className="mk-legal-next"><FileText aria-hidden="true" /><div><b>{isPrivacy ? 'Also review the Terms of Use' : 'Also review the Privacy Policy'}</b><p>Understand the full relationship between product access, connected data, and AI-generated guidance.</p></div><Link to={isPrivacy ? '/terms' : '/privacy'}>Open page <ArrowRight aria-hidden="true" /></Link></div></article></div></section>
  </MarketingShell>;
};

export default LegalPage;
