import { Link } from 'react-router-dom';
import {
  ArrowRight, BarChart3, BookOpen, BrainCircuit, CalendarDays, Check,
  Code2, FileSearch, Gauge, MessageSquareText, Route, Sparkles, Target, Trophy,
} from 'lucide-react';
import { CTASection, MarketingShell, PageHero, usePageMeta } from '../components/marketing/MarketingShell';

const capabilities = [
  ['Profile intelligence', 'Repository languages, complexity, project patterns, and contribution signals become a role-aware skill profile.', BrainCircuit],
  ['Project recommendations', 'Generate portfolio projects selected to strengthen the areas your current work does not yet prove.', Target],
  ['Phased roadmaps', 'Break each recommended project into clear phases, objectives, technologies, methodologies, and milestones.', Route],
  ['Task generation', 'Turn a roadmap phase into specific, actionable work inside the execution workspace.', Code2],
  ['Learning materials', 'Keep phase-relevant resources next to the tasks they support instead of collecting disconnected bookmarks.', BookOpen],
  ['AI mentor chat', 'Ask questions with project and roadmap context available throughout the application.', MessageSquareText],
  ['Repository analysis', 'Generate structured observations, scores, feedback, and suggested improvements for connected repositories.', FileSearch],
  ['Build Day scheduling', 'Plan focused sessions manually or automatically and optionally synchronize them to Google Calendar.', CalendarDays],
  ['Progress analytics', 'Track project completion, contribution consistency, repository signals, skill movement, and activity.', BarChart3],
  ['Achievement system', 'Recognize meaningful development milestones through twelve portfolio and consistency badges.', Trophy],
];

const Product = () => {
  usePageMeta('Product', 'Explore GitMentor skill analysis, personalized roadmaps, AI mentorship, repository review, Build Days, and developer progress analytics.');
  return <MarketingShell>
    <PageHero eyebrow="PRODUCT OVERVIEW" title={<>One system for deliberate <span>developer growth.</span></>} description="GitMentor connects analysis, planning, execution, feedback, and progress so every feature contributes to a stronger body of work.">
      <div className="mk-actions"><Link className="mk-button mk-button-primary" to="/login">Start with your GitHub <ArrowRight aria-hidden="true" /></Link><Link className="mk-button mk-button-secondary" to="/how-it-works">See the workflow</Link></div>
    </PageHero>

    <section className="mk-subnav"><div className="mk-container"><a href="#analyze">Analyze</a><a href="#plan">Plan</a><a href="#build">Build</a><a href="#review">Review</a><a href="#measure">Measure</a></div></section>

    <section className="mk-section mk-product-chapter" id="analyze"><div className="mk-container mk-chapter-grid"><div className="mk-chapter-copy"><span className="mk-chapter-number">01 / ANALYZE</span><div className="mk-card-icon"><BrainCircuit aria-hidden="true" /></div><h2>Understand what your GitHub already proves.</h2><p>GitMentor turns repository metadata and development patterns into an understandable skill profile. The goal is not to reduce you to a score. It is to make the strongest and weakest portfolio signals visible.</p><ul><li><Check aria-hidden="true" /> Role-aligned strengths and gaps</li><li><Check aria-hidden="true" /> Language and repository evidence</li><li><Check aria-hidden="true" /> Explainable recommendations</li></ul></div><div className="mk-ui-panel mk-skill-panel"><header><span>SKILL PROFILE</span><b>Target · Full-stack developer</b></header><div className="mk-skill-score"><span><b>72</b><small>OVERALL SIGNAL</small></span><div><p><b>Frontend architecture</b><small>Strong evidence across 6 repositories</small></p><i><em style={{ width: '86%' }} /></i><p><b>API design</b><small>Developing evidence across 3 repositories</small></p><i><em style={{ width: '64%' }} /></i><p><b>Automated testing</b><small>Opportunity area</small></p><i><em style={{ width: '38%' }} /></i></div></div><footer><Sparkles aria-hidden="true" /> Recommended next signal: integration testing</footer></div></div></section>

    <section className="mk-section mk-product-chapter alt" id="plan"><div className="mk-container mk-chapter-grid"><div className="mk-chapter-copy"><span className="mk-chapter-number">02 / PLAN</span><div className="mk-card-icon"><Route aria-hidden="true" /></div><h2>Move from skill gap to credible project.</h2><p>AI-generated recommendations become complete roadmaps, not vague prompts. Choose a timeline, understand the purpose of each phase, and know what “finished” should demonstrate.</p><ul><li><Check aria-hidden="true" /> Aggressive, moderate, or relaxed pacing</li><li><Check aria-hidden="true" /> Technology and methodology guidance</li><li><Check aria-hidden="true" /> Phase objectives and outcomes</li></ul></div><div className="mk-ui-panel mk-roadmap-panel"><header><span>PORTFOLIO OS ROADMAP</span><b>MODERATE · 8 WEEKS</b></header><div className="mk-roadmap-line"><article className="done"><span><Check aria-hidden="true" /></span><div><small>PHASE 01 · COMPLETE</small><b>Foundation and architecture</b><p>5 tasks · 3 learning materials</p></div></article><article className="active"><span>02</span><div><small>PHASE 02 · IN PROGRESS</small><b>Authentication and persistence</b><p>3 of 7 tasks · Next Build Day today</p></div></article><article><span>03</span><div><small>PHASE 03</small><b>Product intelligence</b><p>6 tasks · 2 repository milestones</p></div></article><article><span>04</span><div><small>PHASE 04</small><b>Testing and release</b><p>5 tasks · Portfolio review</p></div></article></div></div></div></section>

    <section className="mk-section mk-product-chapter" id="build"><div className="mk-container mk-chapter-grid"><div className="mk-chapter-copy"><span className="mk-chapter-number">03 / BUILD</span><div className="mk-card-icon"><Code2 aria-hidden="true" /></div><h2>Keep the plan, learning, and help in one workspace.</h2><p>Open a phase and everything needed to act is already together: generated tasks, linked resources, project context, completion state, scheduling, and the AI mentor.</p><ul><li><Check aria-hidden="true" /> Inline task breakdowns</li><li><Check aria-hidden="true" /> Persistent learning resources</li><li><Check aria-hidden="true" /> Context-aware mentor assistance</li></ul></div><div className="mk-ui-panel mk-build-panel"><header><span>EXECUTION WORKSPACE</span><b>PHASE 02 / 43%</b></header><div className="mk-build-columns"><aside><small>LEARNING MATERIALS</small><div><BookOpen aria-hidden="true" /><p><b>GitHub OAuth flow</b><span>Official documentation</span></p></div><div><BookOpen aria-hidden="true" /><p><b>JWT threat model</b><span>Security guide</span></p></div></aside><main><small>TASKS</small><label><span className="checked"><Check aria-hidden="true" /></span><p><b>Define protected routes</b><em>Completed</em></p></label><label><span /><p><b>Handle callback exchange</b><em>In progress</em></p></label><label><span /><p><b>Add session expiry tests</b><em>Queued</em></p></label></main></div><footer><MessageSquareText aria-hidden="true" /><p><b>Ask GitMentor</b><span>What should I test around the OAuth state?</span></p><ArrowRight aria-hidden="true" /></footer></div></div></section>

    <section className="mk-section mk-product-chapter alt" id="review"><div className="mk-container mk-chapter-grid"><div className="mk-chapter-copy"><span className="mk-chapter-number">04 / REVIEW</span><div className="mk-card-icon"><FileSearch aria-hidden="true" /></div><h2>Turn repository feedback into the next improvement.</h2><p>Request AI analysis when you are ready to inspect a repository. GitMentor surfaces observations with clear severity, reasoning, and suggested solutions so feedback stays actionable.</p><ul><li><Check aria-hidden="true" /> Structured repository insights</li><li><Check aria-hidden="true" /> Suggested solutions</li><li><Check aria-hidden="true" /> Context retained for mentor questions</li></ul></div><div className="mk-ui-panel mk-review-panel"><header><span>REPOSITORY ANALYSIS</span><b>portfolio-os / main</b></header><div className="mk-review-score"><Gauge aria-hidden="true" /><span><b>84</b><small>QUALITY SIGNAL</small></span><p>Strong separation of concerns with two reliability improvements recommended.</p></div><article><span className="warning">HIGH VALUE</span><div><b>OAuth state is not invalidated after every failure path</b><p>Delete the stored state record before redirecting from terminal callback failures.</p></div></article><article><span>IMPROVEMENT</span><div><b>Repository service needs a focused integration test</b><p>Cover token expiry and a partial upstream response.</p></div></article></div></div></section>

    <section className="mk-section mk-product-chapter" id="measure"><div className="mk-container mk-chapter-grid"><div className="mk-chapter-copy"><span className="mk-chapter-number">05 / MEASURE</span><div className="mk-card-icon"><BarChart3 aria-hidden="true" /></div><h2>Track evidence of growth, not vanity alone.</h2><p>GitMentor combines roadmap completion, contribution consistency, repository progress, language distribution, and achievement milestones into a view of sustained development.</p><ul><li><Check aria-hidden="true" /> Project and phase progress</li><li><Check aria-hidden="true" /> Contribution and streak context</li><li><Check aria-hidden="true" /> Twelve meaningful achievements</li></ul></div><div className="mk-ui-panel mk-analytics-panel"><header><span>DEVELOPER ANALYTICS</span><b>LAST 90 DAYS</b></header><div className="mk-metric-row"><article><small>BUILD SESSIONS</small><b>24</b><span>+18% this period</span></article><article><small>PROJECT PROGRESS</small><b>68%</b><span>3 phases complete</span></article><article><small>ACTIVE STREAK</small><b>16d</b><span>Personal best</span></article></div><div className="mk-chart"><div style={{ height: '32%' }} /><div style={{ height: '48%' }} /><div style={{ height: '40%' }} /><div style={{ height: '62%' }} /><div style={{ height: '55%' }} /><div style={{ height: '76%' }} /><div style={{ height: '88%' }} /><span>Focused building time · weekly</span></div></div></div></section>

    <section className="mk-section mk-capability-index"><div className="mk-container"><div className="mk-section-heading"><span className="mk-eyebrow"><Sparkles aria-hidden="true" /> CAPABILITY INDEX</span><h2>The complete GitMentor toolkit.</h2><p>Ten connected capabilities supporting the full developer growth loop.</p></div><div className="mk-capability-grid">{capabilities.map(([title, body, Icon], index) => <article key={title}><span>{String(index + 1).padStart(2, '0')}</span><Icon aria-hidden="true" /><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <CTASection title="Build the next project your profile needs." />
  </MarketingShell>;
};

export default Product;
